name: ZMusic
main: me.zhenxin.zmusic.ZMusicBukkit
version: ${version}
api-version: '1.13'
author: ZhenXin
description: 支持 Bukkit、BungeeCord 和 Velocity 的游戏内音乐插件
folia-supported: true
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  zm:
    usage: /zm help
    description: 音乐指令，输入 /zm 后按 Tab 查看可用操作
    aliases:
      - zmusic
      - music
permissions:
  zmusic.use:
    default: true
    description: zmusic.use
  zmusic.bypass:
    default: op
    description: zmusic.bypass
  zmusic.playall:
    default: op
    description: zmusic.playall
  zmusic.admin:
    default: op
    description: zmusic.admin
