plugins {
    alias(libs.plugins.shadow)
}

version = '2.5.0'

dependencies {

    compileOnly libs.placeholderapi
}

build {
    dependsOn shadowJar
}

processResources {
    inputs.property "version", project.version

    filesMatching("plugin.yml") {
        expand "version": project.version
    }
}
